version: '3'
services:
  db:
    restart: always
    image: postgres:10.23-alpine
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mastodon", "-d", "mastodon"]
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mastodon
      POSTGRES_DB: mastodon
      POSTGRES_PASSWORD: Mastodon

  redis:
    restart: always
    image: redis:6.0-alpine
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - ./redis:/data

  web:
    depends_on:
      - db
      - redis

  streaming:
    depends_on:
      - db
      - redis

  sidekiq:
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    restart: always
    env_file: .env.production
    volumes:
      - ./tmp/nginx/html:/usr/share/nginx/html
      - ./tmp/nginx/templates:/etc/nginx/templates
      - ./tmp/nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    networks:
      - external_network
      - internal_network
    depends_on:
      - web
      - streaming
