# ストレージ移行完了させるまでのファイル同期を定期的に実行するcron
# 無料範囲を超えない程度に実行する
# 1回でだいたい5分前後かかる（ローカルPCだと）
name: Ikatodon Storage Rclone Sync

on:
  schedule:
    - cron: '0 */2 * * *' # 2時間ごと
  workflow_dispatch: # 手動実行も可能に

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Rclone Sync
        run: |
          docker run --rm \
            -e RCLONE_CONFIG_WASABI_TYPE=s3 \
            -e RCLONE_CONFIG_WASABI_PROVIDER=Wasabi \
            -e RCLONE_CONFIG_WASABI_ACCESS_KEY_ID="${{ secrets.WASABI_ACCESS_KEY_ID }}" \
            -e RCLONE_CONFIG_WASABI_SECRET_ACCESS_KEY="${{ secrets.WASABI_SECRET_ACCESS_KEY }}" \
            -e RCLONE_CONFIG_WASABI_REGION=us-west-1 \
            -e RCLONE_CONFIG_WASABI_ENDPOINT=s3.us-west-1.wasabisys.com \
            -e RCLONE_CONFIG_B2_TYPE=b2 \
            -e RCLONE_CONFIG_B2_ACCOUNT="${{ secrets.B2_ACCOUNT }}" \
            -e RCLONE_CONFIG_B2_KEY="${{ secrets.B2_KEY }}" \
            rclone/rclone sync wasabi:ikatodon-media b2:ikatodon-media \
            --fast-list \
            --size-only \
            --transfers 32 \
            --checkers 64
